name: CI Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-node@v4
      with:
        node-version: 18

    # Backend
    - name: Install Backend
      run: |
        cd backend
        npm install

    # Frontend (FIXED PATH)
    - name: Install Frontend
      run: |
        cd frontend/employee-salary-frontend
        npm install

    - name: Build Frontend
      run: |
        cd frontend/employee-salary-frontend
        npm run build

    - name: Security Check
      run: |
        npm audit --audit-level=high || true